on: [push]

jobs:
  eval:
    runs-on: ubuntu-latest
    name: Arr.ai eval
    steps:
    - name: Eval hello world
      id: hello
      uses: orlade/arrai-action@v1
      with:
        eval: '"Hello, world!"'
    # Use the output from the `hello` step
    - name: Get the output
      run: echo "${{ steps.hello.outputs.result }}"
